name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    env:
      DATABASE_URL: "https://fake.com"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Type Checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint
